#!/bin/bash

##############################################################################
##
##  SODABOX Server start up script for UN*X
##
##############################################################################

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}
info ( ) {
    echo "$*"
}


if [ -n "$1" ] ; then
	echo $1
else
	die "ERROR: where is a configuration file? huh ?"
fi

APP_HOME="`pwd -P`"
APP_MODS="$APP_HOME/mods"
CONF_FILE=$1  
# "$APP_HOME/conf/$1.json"

#if [ -n "$1" ] ; then
#	CONF_FILE=$1
#fi


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

export VERTX_HOME=$APP_HOME/bin/vertx
export VERTX_MODS=$APP_MODS
info ".
***********************************************
* APP_HOME   : $APP_HOME
* APP_MODS   : $APP_MODS
* VERTX_HOME : $VERTX_HOME
* JAVA_HOME  : $JAVA_HOME
* CONF_FILE  : $CONF_FILE
***********************************************
."

echo "vertx run io.sodabox.starter.Main -conf $CONF_FILE -cp $APP_HOME/lib/* -instances 1"
exec vertx run io.sodabox.starter.Main -conf "$CONF_FILE" -cp "$APP_HOME"/lib/* -instances 1
